# Generated by Django 5.2.4 on 2025-10-02 23:49

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioMarker',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(blank=True, max_length=100, null=True)),
                ('commonName', models.CharField(blank=True, max_length=255, null=True)),
                ('uniProtKB', models.CharField(blank=True, max_length=100, null=True)),
                ('pdb', models.CharField(blank=True, max_length=100, null=True)),
                ('molecularWeight', models.FloatField(blank=True, null=True)),
                ('molecularLength', models.IntegerField(blank=True, null=True)),
                ('aaSequence', models.CharField(blank=True, max_length=4096, null=True)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('biomType', models.CharField(max_length=50)),
                ('uploadedBy', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(db_column='__v', default=0)),
                ('imagePath', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'bioMarker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_column='__v', default=0)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'counters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('createdBy', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('members', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.ObjectIdField(), blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(db_column='__v', default=0)),
            ],
            options={
                'db_table': 'study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('results', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=2048), blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('createdBy', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(db_column='__v', default=0)),
            ],
            options={
                'db_table': 'studyResult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyVariable',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(max_length=100)),
                ('answerOptions', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('isSearchable', models.BooleanField(default=False)),
                ('isRange', models.BooleanField(default=False)),
                ('isUnique', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('study', django_mongodb_backend.fields.ObjectIdField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(db_column='__v', default=0)),
            ],
            options={
                'db_table': 'studyVariable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('userType', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(db_column='__v', default=0)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
