# Generated by Django 5.2.4 on 2025-12-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place ID'),
        ),
    ]
