# Generated by Django 6.0.1 on 2026-01-29 21:44

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('isRange', models.BooleanField(default=False, verbose_name='Is Range')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], default='TEXT', max_length=100, verbose_name='Type')),
                ('field', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('IMAGE', 'Image'), ('File', 'File'), ('DATE', 'Date'), ('TEXT', 'Text')], default='TEXT', max_length=100, verbose_name='Field')),
                ('isSearchable', models.BooleanField(default=False, verbose_name='Is Searchable')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('isUnique', models.BooleanField(default=False, verbose_name='Is Unique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BioMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aaSequence', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Amino Acid Sequence')),
                ('biomType', models.CharField(choices=[('EXISTING', 'Existing'), ('NEW', 'New')], default='EXISTING', max_length=50, verbose_name='Biomarker Type')),
                ('commonName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Common Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='biomarkers/', verbose_name='Image')),
                ('molecularLength', models.IntegerField(default=0, verbose_name='Molecular Length')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ncib', models.CharField(blank=True, max_length=255, null=True, verbose_name='NCIB ID')),
                ('pdb', models.CharField(blank=True, max_length=255, null=True, verbose_name='PDB ID')),
                ('shortName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Status')),
                ('type', models.CharField(choices=[('PROTEIN', 'Protein'), ('RNA', 'RNA'), ('DNA', 'DNA')], default='PROTEIN', max_length=50, verbose_name='Type')),
                ('uniProtKB', models.CharField(blank=True, max_length=255, null=True, verbose_name='UniProtKB ID')),
                ('molecularWeight', models.FloatField(default=0, verbose_name='Molecular Weight')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('administeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administeredBioMarkers', to=settings.AUTH_USER_MODEL, verbose_name='Administered By')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploadedBioMarkers', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('fullName', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.F('firstName'), models.Value(' '), models.F('lastName')), output_field=models.CharField(max_length=101), verbose_name='Full Name')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, help_text='Profile photo URL', max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdPatients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visitedAt', models.DateTimeField(auto_now_add=True, verbose_name='Visited At')),
                ('notes', models.TextField(blank=True, null=True)),
                ('isCurrent', models.BooleanField(default=False, verbose_name='Is Current Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='main.patient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPlaces', to='settings.place')),
            ],
            options={
                'verbose_name': 'Patient Place',
                'verbose_name_plural': 'Patient Places',
                'ordering': ['-visitedAt'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('CKDU', 'ckdu')], max_length=50, null=True, verbose_name='Category')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('variables', models.ManyToManyField(blank=True, null=True, related_name='studies', to='main.studyvariable', verbose_name='Variables')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyVariableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.studyvariable', verbose_name='Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255, verbose_name='Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Status')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('administeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administeredStudies', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdStudies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userStudies', to='main.patient')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userStudies', to='main.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Value')),
                ('studyVariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.studyvariable', verbose_name='Study Variable')),
                ('userStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.userstudy', verbose_name='User Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('file_url', models.CharField(max_length=500, verbose_name='File URL')),
                ('file_name', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('mapping', models.JSONField(default=dict, verbose_name='Column Mapping')),
                ('column_types', models.JSONField(default=dict, verbose_name='Column Types')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Processed Rows')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Imported Count')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Updated Count')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Skipped Count')),
                ('error_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('consecutive_errors', models.IntegerField(default=0, verbose_name='Consecutive Errors')),
                ('patients_created', models.IntegerField(default=0, verbose_name='Patients Created')),
                ('variables_created', models.IntegerField(default=0, verbose_name='Variables Created')),
                ('errors', models.JSONField(default=list, verbose_name='Error Details')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('paused_reason', models.CharField(blank=True, help_text='manual, consecutive_errors, or server_restart', max_length=50, null=True, verbose_name='Pause Reason')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Task ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataImportJobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importJobs', to='main.study', verbose_name='Study/Dataset')),
            ],
            options={
                'verbose_name': 'Data Import Job',
                'verbose_name_plural': 'Data Import Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['study', 'status'], name='main_dataim_study_i_df0a3a_idx'), models.Index(fields=['created_by', 'status'], name='main_dataim_created_dcf49e_idx')],
            },
        ),
    ]
