# Generated by Django 5.2.4 on 2025-10-06 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('isRange', models.BooleanField(default=False, verbose_name='Is Range')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], default='TEXT', max_length=100, verbose_name='Type')),
                ('field', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('IMAGE', 'Image'), ('File', 'File'), ('DATE', 'Date'), ('TEXT', 'Text')], default='TEXT', max_length=100, verbose_name='Field')),
                ('isSearchable', models.BooleanField(default=False, verbose_name='Is Searchable')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('isUnique', models.BooleanField(default=False, verbose_name='Is Unique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BioMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aaSequence', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Amino Acid Sequence')),
                ('biomType', models.CharField(choices=[('EXISTING', 'Existing'), ('NEW', 'New')], default='EXISTING', max_length=50, verbose_name='Biomarker Type')),
                ('commonName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Common Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='biomarkers/', verbose_name='Image')),
                ('molecularLength', models.IntegerField(default=0, verbose_name='Molecular Length')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ncib', models.CharField(blank=True, max_length=255, null=True, verbose_name='NCIB ID')),
                ('pdb', models.CharField(blank=True, max_length=255, null=True, verbose_name='PDB ID')),
                ('shortName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Status')),
                ('type', models.CharField(choices=[('PROTEIN', 'Protein'), ('RNA', 'RNA'), ('DNA', 'DNA')], default='PROTEIN', max_length=50, verbose_name='Type')),
                ('uniProtKB', models.CharField(blank=True, max_length=255, null=True, verbose_name='UniProtKB ID')),
                ('molecularWeight', models.FloatField(default=0, verbose_name='Molecular Weight')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('administeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administeredBioMarkers', to=settings.AUTH_USER_MODEL, verbose_name='Administered By')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploadedBioMarkers', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('CKDU', 'ckdu')], max_length=50, null=True, verbose_name='Category')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reference', models.CharField(max_length=255, verbose_name='Reference')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('variables', models.ManyToManyField(related_name='studies', to='main.studyvariable', verbose_name='Variables')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyVariableAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.studyvariable', verbose_name='Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255, verbose_name='Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50, verbose_name='Status')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('administeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administeredStudies', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdStudies', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userStudies', to='main.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('studyVariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studyvariable', verbose_name='Study Variable')),
                ('userStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userstudy', verbose_name='User Study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
