# Generated by Django 5.2.4 on 2025-10-06 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='study',
            name='variables',
            field=models.ManyToManyField(blank=True, null=True, related_name='studies', to='main.studyvariable', verbose_name='Variables'),
        ),
    ]
