# Generated by Django 6.0.5 on 2026-05-20 15:26

from django.db import migrations, models


def set_tested_date(apps, schema_editor):
    UserStudy = apps.get_model('main', 'UserStudy')
    for study in UserStudy.objects.all():
        if study.created_at:
            study.testedDate = study.created_at
            study.save(update_fields=['testedDate'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_biomarker_aasequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudy',
            name='testedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tested Date'),
        ),
        migrations.RunPython(set_tested_date, reverse_code=migrations.RunPython.noop),
    ]
