# Generated by Django 5.2.4 on 2025-10-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_study_members_alter_study_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyresult',
            name='studyVariable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.studyvariable', verbose_name='Study Variable'),
        ),
        migrations.AlterField(
            model_name='studyresult',
            name='userStudy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.userstudy', verbose_name='User Study'),
        ),
        migrations.AlterField(
            model_name='studyresult',
            name='value',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Value'),
        ),
    ]
