# Generated by Django 5.2.4 on 2025-10-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userstudy_user_patient_userstudy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PID'),
        ),
    ]
