# Generated by Django 5.2.4 on 2025-11-02 19:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_patient_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
        migrations.AddField(
            model_name='patient',
            name='fullName',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(models.F('firstName'), models.Value(' '), models.F('lastName')), output_field=models.CharField(max_length=101), verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='study',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference'),
        ),
    ]
