# Generated by Django 5.2.4 on 2025-11-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_patient_email_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
