# Generated by Django 5.2.4 on 2025-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_patient_email_remove_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.CharField(blank=True, help_text='Profile photo URL', max_length=500, null=True),
        ),
    ]
