# Generated by Django 5.2.4 on 2025-12-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_patient_photo'),
        ('settings', '0002_alter_place_placeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visitedAt', models.DateTimeField(auto_now_add=True, verbose_name='Visited At')),
                ('notes', models.TextField(blank=True, null=True)),
                ('isCurrent', models.BooleanField(default=False, verbose_name='Is Current Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='main.patient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPlaces', to='settings.place')),
            ],
            options={
                'verbose_name': 'Patient Place',
                'verbose_name_plural': 'Patient Places',
                'ordering': ['-visitedAt'],
            },
        ),
    ]
