# Generated by Django 5.2.4 on 2026-01-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_patient_latitude_patient_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('file_url', models.CharField(max_length=500, verbose_name='File URL')),
                ('file_name', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('mapping', models.JSONField(default=dict, verbose_name='Column Mapping')),
                ('column_types', models.JSONField(default=dict, verbose_name='Column Types')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total Rows')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Processed Rows')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Imported Count')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Updated Count')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='Skipped Count')),
                ('error_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('consecutive_errors', models.IntegerField(default=0, verbose_name='Consecutive Errors')),
                ('patients_created', models.IntegerField(default=0, verbose_name='Patients Created')),
                ('variables_created', models.IntegerField(default=0, verbose_name='Variables Created')),
                ('errors', models.JSONField(default=list, verbose_name='Error Details')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('paused_reason', models.CharField(blank=True, help_text='manual, consecutive_errors, or server_restart', max_length=50, null=True, verbose_name='Pause Reason')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Task ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataImportJobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importJobs', to='main.study', verbose_name='Study/Dataset')),
            ],
            options={
                'verbose_name': 'Data Import Job',
                'verbose_name_plural': 'Data Import Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['study', 'status'], name='main_dataim_study_i_df0a3a_idx'), models.Index(fields=['created_by', 'status'], name='main_dataim_created_dcf49e_idx')],
            },
        ),
    ]
