# Generated by Django 5.2 on 2025-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countryCode',
            field=models.CharField(blank=True, default=94, max_length=5, verbose_name='Country Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NIC Number'),
            preserve_default=False,
        ),
    ]
