# Generated by Django 5.2.4 on 2025-09-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture'),
        ),
    ]
