# Generated by Django 5.2 on 2025-05-22 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_countrycode_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Device Name')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('macAddress', models.CharField(max_length=255, verbose_name='MAC Address')),
                ('deviceType', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop')], default='DESKTOP', max_length=255, verbose_name='Device Type')),
                ('publicId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('lastSeen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
