# Generated by Django 6.0.5 on 2026-10-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(max_length=32, verbose_name='Key Prefix'),
        ),
    ]
