# Generated by Django 5.2 on 2025-05-22 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Channel Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('publicId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('s3FolderPath', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Folder Path')),
                ('icecastMountPoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icecast Mount Point')),
                ('icecastPassword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icecast Password')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-createdAt'],
            },
        ),
    ]
