# Generated by Django 5.2 on 2025-05-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='updatedAt',
        ),
    ]
