# Generated by Django 5.2 on 2025-05-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_channel_options_remove_channel_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
    ]
