# Generated by Django 5.2 on 2025-06-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_channel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='icecastMountPoint',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='icecastPassword',
        ),
        migrations.CreateModel(
            name='IceCastServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('icecastMountPoint', models.CharField(max_length=255, unique=True, verbose_name='Icecast Mount Point')),
                ('icecastPassword', models.CharField(max_length=255, verbose_name='Icecast Password')),
                ('isActive', models.BooleanField(default=False, verbose_name='Is Active')),
                ('isSecret', models.BooleanField(default=False, verbose_name='Is Secret')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icecast_servers', to='authentication.channel', verbose_name='Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
