# Generated by Django 5.2 on 2025-06-25 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_channel_icecastmountpoint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fullName",
        ),
    ]
