# Generated by Django 5.2 on 2025-06-25 22:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_remove_user_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fullName",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    models.F("firstName"), models.Value(" "), models.F("lastName")
                ),
                output_field=models.CharField(max_length=101),
                verbose_name="Full Name",
            ),
        ),
    ]
