name: Quality Assurance

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH 

      - name: Install project dependencies
        run: make sync

      - name: Activate uv environment
        run: source .venv/bin/activate

      - name: Install Ruff
        run: uv add ruff

      - name: Lint with Ruff
        run: .venv/bin/ruff check